### PR TITLE
fix HPA api version

### PR DESCRIPTION
**Pull request by Noamshmueli**
fix HPA api version to `autoscaling/v2`

### CODE REVIEW

**Comment by pmint93** [comment]
@Noamshmueli  To keep this chart compatible with older k8s version, I suggest it detect kubernetes version and use the right apiVersion. #16 pointed out that we can use `semverCompare` function and `.Capabilities.KubeVersion.GitVersion` to do so

**Comment by Noamshmueli** [comment]
@pmint93  I got you and look into it but seems like `autoscaling/v2` is the stable one so we can set it hradcoded

**Comment by pmint93** [comment]
> @pmint93 I got you and look into it but seems like `autoscaling/v2` is the stable one so we can set it hradcoded

of course it is stable version, but what I mean is: `autoscaling/v2` is available since v1.23, so if user running version older than v1.23 (eg: v1.22), the installation will fail

**Comment by Noamshmueli** [comment]
Done @pmint93

**Review by pmint93 — APPROVED** [review]

**Pull request merged**
