### PR TITLE
Added options to create tls secrets using values

### PR DESCRIPTION
**Pull request by seocam**

### CODE REVIEW

**Comment by pmint93** [comment]
I think this is not necessary, you can manually create the secret and put it's name in `ingress.tls[0].secretName`

Don't want this chart to be complicated

**Comment by seocam** [comment]
I've added that because I cannot deploy in our cluster without using helm. To "manually" create a secret I'd need to create a helm just for the secret :(

But I understand your position. Since most clusters are using cert-manager this shouldn't be a problem for the vast majority of users.

I guess the best route for me would be to keep a fork with this change.

**Comment by pmint93** [comment]
I'm curious how your cluster is strictly depends on helm. Helm is just call the api to deploy your manifests, so I expect you could do `kubectl create -f your-tls-secret.yaml`

**Comment by seocam** [comment]
It's not the cluster itself that depends on helm.

We have a company police that says that applications must be installed using helm charts. Developers don't have access to the cluster, to deploy something we add a charts directory to our org repo and in some specific branches that will deploy the chart in the clusters for us (depending on the branch it goes to a different cluster and/or namespace).

We do try to have everything as most upstream as possible to contribute with the community but in some cases (like here) our changes don't fit the interests of the upstream helm project and because of that we need to keep our fork.

I hope that this fulfills your curiosity :wink:

**Comment by pmint93** [comment]
Thanks for that. And so, I'm sorry that you have to keep doing it that way. Closing this PR :)

**Pull request closed without merging**
