### PR TITLE
Added options to configure MB_COOKIE_SAMESITE

### PR DESCRIPTION
**Pull request by seocam**
Added the option to configure `MB_COOKIE_SAMESITE` since this is available in current metabase version (v0.39.3).
https://github.com/metabase/metabase/blob/v0.39.3/src/metabase/config.clj#L112-L121

### CODE REVIEW

**Comment by pmint93** [comment]
Hi @seocam 

Please update values.yaml accordingly, and bump the chart version in Chart.yaml

If `MB_COOKIE_SAMESITE` only available since v0.39.3, please bump the metabase version also

Thanks for your contribution !

**Comment by seocam** [comment]
> Hi @seocam
> 
> Please update values.yaml accordingly, and bump the chart version in Chart.yaml
> 
> If `MB_COOKIE_SAMESITE` only available since v0.39.3, please bump the metabase version also
> 
> Thanks for your contribution !

Done

**Comment by pmint93** [comment]
Oops, you need to bump the chart version in `Chart.yaml`

And still, there're few more places that reference the metabase version, in `Chart.yaml` and `README.md` (please use search all function to find and make sure they got changed to v0.39.3)

**Comment by seocam** [comment]
Done :)

**Pull request merged**
