### PR TITLE
Allow all helm features for extraEnv values

### PR DESCRIPTION
**Pull request by tessig**
By just rendering extraEnv as yaml we can use all helm features like get the env value from configmaps and secrets

### CODE REVIEW

**Comment by pmint93** [comment]
Brilliant ! @tessig

And so we can deprecate the `envFromSecret` for good ?

But before this PR can be merged, please also bump the chart version in `Chart.yaml`

**Comment by tessig** [comment]
@pmint93 since removing `envFromSecret` would be a breaking change, I suggest to first only merge this change.
Or do you prefer a major version change at this point?

**Comment by pmint93** [comment]
@tessig I prefer major version change

**Comment by pmint93** [comment]
@tessig it seem we have problem with empty extraEnv, the result is yaml syntax error

**Pull request merged**
