### PR TITLE
Upgrade to v0.43.1; Change Postgres connection string;

### PR DESCRIPTION
**Pull request by m-wrzr**
Hey, I updated the Postgres connection string according to the [metabase docs](https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html) because the current schema didn't work for me.

Also bumped up the Metabase version to v0.43.1

If there is anything else that needs changing, please let me know.

### CODE REVIEW

**Comment by pmint93** [comment]
@m-wrzr thanks for contributing !

However, that just the example value, there's many format for connection URI and you always can edit this value to suite your deployment.

So this PR making no sense

**Comment by m-wrzr** [comment]
I know that it's an example, but if you adapt the current connection string `...user:password@host...` it won't work, because they changed the format to use user/password as a suffix `host:5432/metabase?user=<username>&password=<password>`.

At least for me formatting the connection string as in the `values.yml` didn't work.

**Comment by pmint93** [comment]
I doubt that URI format is changed. Instead,  it just your postgres deployment that did not support the `user@password` kind of URI.

Do you have any clue of the old URI format is deprecated ?

**Comment by m-wrzr** [comment]
https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html#postgres 
https://discourse.metabase.com/t/metabase-not-connecting-to-postgres-database/18855/3

**Comment by pmint93** [comment]
Seem fair 👍

**Pull request merged**
